sudo: false
dist: trusty
language: java

matrix:
  include:
# 8
    - jdk: oraclejdk8
    - jdk: openjdk8
# 9
    - jdk: oraclejdk9
    - jdk: openjdk9
# 10
    - jdk: oraclejdk10
    - jdk: openjdk10
# 11
    - jdk: oraclejdk11
    - jdk: openjdk11

script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version